# See http://www.appveyor.com/docs/appveyor-yml for many more options

environment:
  NugetApiKey:
    secure: ChXV2D8zXSj94xqIx58U26/VtF3l93BjteOwKSYY/J8AERvVK1OIHcIrgCpSTDod

# Allow WMF5 (i.e. PowerShellGallery functionality)
image: Visual Studio 2017

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message 
skip_commits:
  message: /updated readme.*|update readme.*s/

build: false

#Kick off the CI/CD pipeline 
test_script:
  - ps: . .\Build\Start-Build.ps1 -Task Deploy